import Head from 'next/head'
import { FC } from 'react'
import { FlexContainer } from 'components/atoms/FlexContainer/FlexContainer'
import { FooterContainer } from 'components/atoms/FooterContainer/FooterContainer'
import { MainContainer } from 'components/atoms/MainContainer/MainContainer'

interface DefaultTemplateProps {
	title?: string
	description?: string
	icon?: string
	children: JSX.Element | JSX.Element[]
	hasFooter?: boolean
	loading?: boolean
}

export const Default: FC<DefaultTemplateProps> = ({
	title = 'GenUI React Starter',
	description = 'Generated by create next app',
	icon = '/favicon.ico',
	children,
	loading,
	hasFooter = true
}) => {
	return (
		<div>
			<Head>
				<title>{title}</title>
				<meta name='description' content={description} />
				<link rel='icon' href={icon} />
			</Head>

			<main>
				<MainContainer>{children}</MainContainer>
			</main>

			{hasFooter && (
				<FooterContainer>
					<FlexContainer>
						<a
							href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
							target='_blank'
							rel='noopener noreferrer'
						>
							Powered by{' '}
							<span>
								<img src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
							</span>
						</a>
					</FlexContainer>
				</FooterContainer>
			)}
		</div>
	)
}
