import Head from 'next/head'
import { FC } from 'react'
import { PageLoadingSpinner } from 'components/atoms'
import styles from 'styles/Home.module.css'

interface DefaultTemplateProps {
	title?: string
	description?: string
	icon?: string
	children: JSX.Element | JSX.Element[]
	hasFooter?: boolean
	loading?: boolean
}

export const Default: FC<DefaultTemplateProps> = ({
	title = 'GenUI React Starter',
	description = 'Generated by create next app',
	icon = '/favicon.ico',
	children,
	loading,
	hasFooter = true
}) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>{title}</title>
				<meta name='description' content={description} />
				<link rel='icon' href={icon} />
			</Head>

			<main className={styles.main}>{loading ? <PageLoadingSpinner /> : children}</main>

			{hasFooter && (
				<footer className={styles.footer}>
					<a
						href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						target='_blank'
						rel='noopener noreferrer'
					>
						Powered by{' '}
						<span className={styles.logo}>
							<img src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
						</span>
					</a>
				</footer>
			)}
		</div>
	)
}
