// import Image from 'next/image'
import Head from 'next/head'
import styles from 'styles/Home.module.css'

/**
 * About page!
 *
 * @returns a component
 */
export default function About() {
	return (
		<div className={styles.container}>
			<Head>
				<title>About page</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/fsavicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>About Page</h1>
			</main>
		</div>
	)
}
