// import Image from 'next/image'
import Head from 'next/head'
import { decrement, increment, useCounter } from 'state/counter'
import { Button } from 'components/button'
import styles from 'styles/Home.module.css'

/**
 * About page!
 *
 * @returns a component
 */
export default function About() {
	const { count } = useCounter()

	return (
		<div className={styles.container}>
			<Head>
				<title>test</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/fsavicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Counter: {count}</h1>
				<div className={styles.buttonContainer}>
					<Button onClick={decrement}>-1</Button>
					<Button onClick={increment}>+1</Button>
				</div>
			</main>
		</div>
	)
}
