import Head from 'next/head'
import Link from 'next/link'
import { CardLink } from 'components/atoms/CardLink'
// import Image from 'next/image'
import styles from 'styles/Home.module.css'

/**
 * Home page!
 *
 * @returns a component
 */
export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to the{' '}
					<a
						rel='noreferrer'
						target='_blank'
						href='https://github.com/generalui/react-nextjs-boilerplate'
					>
						GenUI React Starter!
					</a>
				</h1>

				<p className={styles.description}>
					Get started by editing <code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					<Link
						href='https://github.com/generalui/react-nextjs-boilerplate/blob/main/DEVELOPMENT.md'
						passHref
					>
						<CardLink rel='noreferrer' target='_blank'>
							<h2>Documentation &rarr;</h2>
							<p>Learn how to use this starter project to build robust apps.</p>
						</CardLink>
					</Link>

					<Link href='https://nextjs.org' passHref>
						<CardLink rel='noreferrer' target='_blank'>
							<h2>Next.js &rarr;</h2>
							<p>Learn more about Next.js features and API.</p>
						</CardLink>
					</Link>

					<Link
						href='https://github.com/generalui/react-nextjs-boilerplate/blob/main/DEVELOPMENT.md'
						passHref
					>
						<CardLink rel='noreferrer' target='_blank'>
							<h2>Contributing &rarr;</h2>
							<p>Discover how you can contribute to this project.</p>
						</CardLink>
					</Link>

					<Link href='/counter' passHref>
						<CardLink>
							<h2>Hooks for Redux &rarr;</h2>
							<p>An example of using hooks-for-redux and persisting to cookie storage.</p>
						</CardLink>
					</Link>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<img src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}
